require "spree_core"
require "spree_extension"
require "spree_product_reviews/engine"
require "spree_product_reviews/version"
require "spree_auth_devise"
require "deface"
require "sass/rails"
require "inline_svg"
